[project]
name = "earnie-tr-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mypy>=1.19.1",
    "poethepoet>=0.40.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]

[tools.poethepoet.tasks]
test = "pytest tests"

[tool.setuptools.package-data]
models = ["py.typed"]

[tool.mypy]
python_version = "3.14"
pretty = true
show_error_codes = true
warn_unused_ignores = true

#[mypy]
#ignore_missing_imports = True